site_name: LibDocs
site_description: "機械学習研究のための公式ライブラリ解説"
# Replace `<github-username>` with the actual GitHub account that hosts the repository.
site_url: "https://<github-username>.github.io/LibDocs/"
nav:
  - ホーム: index.md
  - 構成・制御:
      - ガイド: config/index.md
      - Hydra: config/hydra.md
      - OmegaConf: config/omegaconf.md
  - 探索・最適化:
      - ガイド: optimization/index.md
      - Optuna × Hydra × MLflow: optimization/optuna-hydra-mlflow.md
  - 並列実行:
      - ガイド: parallel/index.md
      - multiprocessing: parallel/multiprocessing.md
      - Joblib: parallel/joblib.md
      - Ray: parallel/ray.md
      - Hydra Launchers: parallel/hydra-launcher.md
  - 記録・再現:
      - ガイド: tracking/index.md
      - MLflow Tracking: tracking/mlflow-tracking.md
      - MLflow Projects: tracking/mlflow-projects.md
      - MLflow Model Registry: tracking/mlflow-model-registry.md
  - 構造的管理:
      - ガイド: structure/index.md
      - uv: structure/uv.md
      - venv: structure/venv.md
      - Hydra Runner: structure/hydra-runner.md
      - Talk to My Data Agent: structure/talk-to-my-data-agent.md
theme:
  name: material
  language: ja
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
